Shutting down daemon process if build_runner throws. (#4274)
Consecutive execution of `webdev serve` when `build_runner` throws was causing an errant VM process to hold onto websocket connections, resulting in:
```
WebSocketChannelException: SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = localhost, port = XXXXX
```